# netlify.toml
# This file explicitly tells Netlify where to find functions.

[functions]
  # Specifies the directory where your serverless functions are located.
  directory = "netlify/functions"

# Optional: Specify build settings if needed, but likely not for drag-and-drop
# [build]
#   command = "" # No build command needed for simple static site + functions
#   publish = "." # Publish the root directory

[functions."summarize-and-email"]
  # schedule = "@daily" # This is a predefined expression for once a day, midnight UTC
  # Or for a specific time, e.g., 7 AM UTC:
  schedule = "23 11 * * *"